/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type JSEngine = Engine
export class Engine {
  constructor()
}
export type JSModule = Module
export class Module {
  static fromFile(jsEngine: Engine, path: string): JsModule
}
export type JSStore = Store
export class Store {
  constructor(engine: Engine)
}
export type JSLinker = Linker
export class Linker {
  constructor(engine: Engine)
}
export class WasmFunctionTy { }
export class WasmFunction {
  ty(store: Store): WasmFunctionTy
  call0(store: Store): void
}
export type JSInstance = Instance
export class Instance {
  constructor(store: Store, module: Module)
  getFunc(store: Store, fnName: string): WasmFunction | null
}
